// File generated by Antigravity (manually configured)
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhNSYY56e0h_M3tFE_kTOxpsPP-kMNPVQ',
    appId: '1:557004334628:web:0a9c1c63c398c0d22f5ab1',
    messagingSenderId: '557004334628',
    projectId: 'sales-userapp-nk',
    authDomain: 'sales-userapp-nk.firebaseapp.com',
    storageBucket: 'sales-userapp-nk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOZ2SignoWJ_eq3NNcYswiZl7YRa-mtvQ',
    appId: '1:557004334628:android:61e8f6c410bb19562f5ab1',
    messagingSenderId: '557004334628',
    projectId: 'sales-userapp-nk',
    storageBucket: 'sales-userapp-nk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtlutL42IqqOrRX-XE_RpMLZlKEaEwDhw',
    appId: '1:557004334628:ios:25202e2b880a90492f5ab1',
    messagingSenderId: '557004334628',
    projectId: 'sales-userapp-nk',
    storageBucket: 'sales-userapp-nk.firebasestorage.app',
    iosBundleId: 'com.flutterdevyt.aiapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhNSYY56e0h_M3tFE_kTOxpsPP-kMNPVQ',
    appId: '1:557004334628:web:0a9c1c63c398c0d22f5ab1',
    messagingSenderId: '557004334628',
    projectId: 'sales-userapp-nk',
    authDomain: 'sales-userapp-nk.firebaseapp.com',
    storageBucket: 'sales-userapp-nk.firebasestorage.app',
  );
}
